version: '3.6'

networks:
  retail_network:
    name: retail_network

services:
  mongo-db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    container_name: mongo_db
    networks:
      - retail_network
    volumes:
      - ./mongodb/db/:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: myretaildb
    command: mongod --auth
